### ISSUE TITLE
Document not returned by the same query after update an array field that contains a None value.

### ISSUE THREAD

**Issue by dongxinEric** [FoundationDB/fdb-document-layer#135]
A document got updated was not returned by the same query that correctly returned it before the update.

Reproduce step:

```python

testColl = client['testdb']['testcoll']

testColl.remove()

testColl.drop_indexes()


fullDoc = {'B': [123, None]}


testColl.insert_one(fullDoc)

for i in testColl.find( {u'B': {'$in': [None]}}):
    pprint.pprint(i)

# So far so good

testColl.update({u'B': {'$size': 2}} ,  OrderedDict([('$pop', {u'B': -1})]))


for i in testColl.find( {'B': {'$in': [None]}}):
    pprint.pprint(i)

# See that the record was NOT returned
```

It seems to be related to the `None` element in the array. I **cannot** reproduce it if `B` does not contain a `None`.

**Comment by dongxinEric** [comment]
It seems like whenever there is a `None` in the array and there is an update operation which causes the index of the `None` element changed, this bug will appear.

**Comment by apkar** [comment]
@dongxinEric Can you make this a unit test with `pytest.mark.xfail` [mark](https://docs.pytest.org/en/latest/skipping.html).

**Comment by dongxinEric** [comment]
This is not related to #151. The root cause here is that:

- When storing a non-compacted array value, DocLayer does NOT store it as a sparse array, i.e. it persists all fields including the null fields.
- Now when updating the array field with operators, it DOES try to store it as a sparse array, i.e. it does NOT persist the null fields.
- When DocLayer needs to ***reconstruct*** the document that contains such sparse arrays, it can handle the missing null fields correctly. Good.
- However, when doing queries which does not deserialize the whole field, `doPathExpansion()` will see a None value returned for certain indexes in that array and will NOT try to fill in a null for it. As a result of that, certain query against null values in an array, for example `{'B': {'$in': [None]}}`, will not hit the records correctly. Even the find command is now missing those documents.

The solution would be:
- simply always store arrays as non-sparse ones,
- or make the behavior consistent, as in modify the insert functions and `doPathExpansion` so that they are also able to store and deal with sparse arrays.

I lean towards latter since I don't really see the need to support sparse array as of right now. It's not hard to add the support in the future.

**Comment by dongxinEric** [comment]
Moved to 1.8.0 milestone.

**Comment by dongxinEric** [comment]
We still want to store the arrays like sparse arrays. Will try fix doPathExpansion
