### ISSUE TITLE
"-Wreturn-type" breaking the build

### ISSUE THREAD

**Issue by apkar** [FoundationDB/fdb-document-layer#16]
We had to disable this warning due to bad code in one place. It should be easy to reproduce by re-enabling this flag [here](https://github.com/FoundationDB/fdb-document-layer/blob/master/src/CMakeLists.txt#L109).

**Comment by dongxinEric** [comment]
To further clarify: this warning/error only happen in Linux using `gcc 4.9.1`. The code can be build just fine even with this flag enabled in macOS using `AppleClang 10.0.0.10001044`.

**Comment by senthil-db-expert** [comment]
@apkar We could fix this, please assign to me.
The return statements were not declared properly in some functions.
