### ISSUE TITLE
"buildInfo" is returning wrong version information

### ISSUE THREAD

**Issue by apkar** [FoundationDB/fdb-document-layer#54]
As reported [here](https://forums.foundationdb.org/t/server-reports-as-being-mongo-api-verson-2-4/1079), mongo shell is returning version 2.4.0. We are compatible with 3.0.0 it should return that instead.

The issue is mongo shell depends on `buildInfo` command response to find out version. We are updating `isMaster` but not `buildInfo`. We should change there too.

Note: Not directly related to this, but with `buildInfo` we don't return anything about git hash or branch information, as we are not really MongoDB. So far, that didn't seem to cause any issues, or we didn't notice yet. We do have a custom command `getdoclayerversion` that gives us more information on Document Layer versions.

**Comment by dongxinEric** [comment]
IMO, the version number would better be defined in some consolidated constant value header file or something like that, instead of a plain string literal.

**Comment by apkar** [comment]
Yeah! We should maintain some kind of map between wire protocol and server version.
