### ISSUE TITLE
Don't build packages part of default build

### ISSUE THREAD

**Issue by apkar** [FoundationDB/fdb-document-layer#60]
At the moment distribution packages are built with default build (with no make targets). `packages` target builds `tar.gz`. Ideally, we should build all packages with `packages` target. This is cleaner and makes default build faster, which is what we usually care in development.

**Comment by senthil-db-expert** [comment]
@apkar Please assign this ticket to me

**Comment by apkar** [comment]
@senthil-db-expert Please check out FoundationDB CMake scripts. I think their packaging scripts are done bit more cleanly.
