### ISSUE TITLE
Add unique index to MongoModel and correctness

### ISSUE THREAD

**Issue by apkar** [FoundationDB/fdb-document-layer#67]
At the moment, we only have unit tests on unique indexes. We should update correctness to test unique indexes. MongoModel doesn't implement indexes as indexes in MongoModel are not necessary to test the correctness of indexes in Doc Layer. But, unique indexes show the difference in behavior in case there can be duplicates. We should update MongoModel to have this check to be consistent with Doc Layer.

**Comment by dongxinEric** [comment]
Now that we have index and unique index in MM, I will enable them in correctness after some future tuning

**Comment by dongxinEric** [comment]
It's added an enabled via https://github.com/FoundationDB/fdb-document-layer/pull/128
