### ISSUE TITLE
Keep listIndexes() response compatible

### ISSUE THREAD

**Issue by apkar** [FoundationDB/fdb-document-layer#93]
Document Layer returns only secondary indexes in response to `listIndexes()`. Mongo drivers expect primary index (on `_id`, which is maintained anyway) also part of the response. It's an easy fix, we might as well do it just to make the drivers happy.

- [x] Include primary index 
- [ ] Add background rebuild info

**Comment by dongxinEric** [comment]
By `Add background rebuild info` do you mean also return whether this is a background built index or not?
